document.getElementById("semester").addEventListener("change", function () {
    const semester = document.getElementById("semester").value;
    const nameSelect = document.getElementById("name");

    // Limpiar el dropdown de nombres
    nameSelect.innerHTML = '<option value="">Seleccionar nombre</option>';

    // JSON con datos ficticios de amigos secretos
    const friends = {
        "primero": {
            "BENAVIDES GARCIA LEANDRO DANIEL": "HOYOS PATIÑO CARLOS ALBERTO",
            "BENAVIDES VELASQUEZ DANIEL FERNANDO": "VALLEJO HURTADO IVAN DAVID",
            "BURBANO MORA JUAN GUILLERMO": "PANTOJA BASTIDAS JORMAN JHONATHAN",
            "CADENA SANCHEZ NICOLAS SANTIAGO": "SIERRA NARVAEZ JUAN CARLOS",
            "CASANOVA AYALA CHARLI REINALDO": "ROSADA RODRIGUEZ NICOLAS ALEJANDRO",
            "CORAL SILVA CRISTIAN CAMILO": "OBANDO ROSERO GABRIEL DAVID",
            "CORDOBA DIAZ OSCAR JULIAN": "LOPEZ LIMAS DANIA ALEJANDRA",
            "CORONEL DELGADO JAIDER": "HOYOS ESTUPIÑAN JUAN FELIPE",
            "DE LA ROSA MAYA JAIRO SEBASTIAN": "OBANDO DIAZ GABRIEL SANTIAGO",
            "DIAZ ORTIZ ANGELA GABRIELA": "TUTALCHA CUATIN AMANDA YANEL",
            "ENRIQUEZ ESPAÑA MIGUEL ANGEL ANDRES": "OBANDO ALVARO KEVIN",
            "ERAZO MONTEZUMA JUAN JOSE": "ROSADA RODRIGUEZ NICOLAS ALEJANDRO",
            "HOYOS ESTUPIÑAN JUAN FELIPE": "MARTINEZ BENAVIDES SAMUEL",
            "HOYOS PATIÑO CARLOS ALBERTO": "ORTEGA CHAMORRO JESUS ALEJANDRO",
            "LOPEZ BOTINA JAVIER ALDAIR": "SALAS TORRES JUAN MARCOS",
            "LOPEZ LIMAS DANIA ALEJANDRA": "CORONEL DELGADO JAIDER",
            "MARTINEZ BENAVIDES SAMUEL": "CADENA SANCHEZ NICOLAS SANTIAGO",
            "MAYA LASSO JHON DEIBY": "CORDOBA DIAZ OSCAR JULIAN",
            "MEFLEH MOREANO HANAN LUCIA": "BENAVIDES VELASQUEZ DANIEL FERNANDO",
            "MORA OBANDO ALVARO KEVIN": "ORTEGA GOMEZ CARLOS EDUARDO",
            "OBANDO ALVARO KEVIN": "MEFLEH MOREANO HANAN LUCIA",
            "OBANDO DIAZ GABRIEL SANTIAGO": "DE LA ROSA MAYA JAIRO SEBASTIAN",
            "OBANDO ROSERO GABRIEL DAVID": "BURBANO MORA JUAN GUILLERMO",
            "OJEDA OSORIO YOSEPH DAVID": "SANTOS MUTIS DANNA MARCELA",
            "ORTEGA CHAMORRO JESUS ALEJANDRO": "ENRIQUEZ ESPAÑA MIGUEL ANGEL ANDRES",
            "ORTEGA GOMEZ CARLOS EDUARDO": "ERAZO MONTEZUMA JUAN JOSE",
            "PANTOJA BASTIDAS JORMAN JHONATHAN": "SIERRA NARVAEZ JUAN CARLOS",
            "ROSADA RODRIGUEZ NICOLAS ALEJANDRO": "CASANOVA AYALA CHARLI REINALDO",
            "ROSALES SOLARTE DAVID SANTIAGO": "LOPEZ BOTINA JAVIER ALDAIR",
            "SALAS TORRES JUAN MARCOS": "CORAL SILVA CRISTIAN CAMILO",
            "SANTACRUZ GORDILLO DANIEL FELIPE": "MAYA LASSO JHON DEIBY",
            "SANTACRUZ VELA JOSE GABRIEL": "OJEDA OSORIO YOSEPH DAVID",
            "SANTOS MUTIS DANNA MARCELA": "LOPEZ LIMAS DANIA ALEJANDRA",
            "SIERRA NARVAEZ JUAN CARLOS": "BENAVIDES GARCIA LEANDRO DANIEL",
            "TUTALCHA CUATIN AMANDA YANEL": "SANTACRUZ GORDILLO DANIEL FELIPE",
            "VALLEJO HURTADO IVAN DAVID": "ROSALES SOLARTE DAVID SANTIAGO"
            // Resto de los nombres del primer semestre...
        },
        "cuarto": {
            "ALVAREZ SOLARTE VALENTINA": "CEBALLOS ERASO JULIAN ANDRES",
            "ARCOS ARCOS CARLOS DAVID": "ESCOBAR ENRIQUEZ DIEGO FERNANDO",
            "CABRERA NARVAEZ JOSE MANUEL": "GORDILLO ROSERO CAMILO SEBASTIAN",
            "CAICEDO JURADO MARIO ANDRES": "JARAMILLO LUNA ANYELI VANESA",
            "CEBALLOS ERASO JULIAN ANDRES": "LOPEZ VELASQUEZ JHON ALEXANDER",
            "CORONADO PARRA JUAN SEBASTIAN": "MADROÑERO REINEL KEVIN NICOLAS",
            "DELGADO MUÑOZ JUAN DAVID": "MUÑOZ TULCAN JULIANA",
            "ERASO GRIJALBA JUAN MANUEL": "VELASQUEZ BENAVIDES VICTOR MANUEL",
            "ERAZO CASTRO KAREN BRIGITH": "ALVAREZ SOLARTE VALENTINA",
            "ESCOBAR ENRIQUEZ DIEGO FERNANDO": "QUENAN ALDERETE CARLOS ANDRES",
            "GORDILLO ROSERO CAMILO SEBASTIAN": "TULCAN CIFUENTES GERMAN ANDRES",
            "JARAMILLO DIAZ JUAN FERNANDO": "VALLEJO ZAMORA MARIA ALEJANDRA",
            "JARAMILLO LUNA ANYELI VANESA": "PASAJENARVAEZ DAVID",
            "LAGOS URBANO DANNA NATALY": "NARVAEZ CABRERA JAIDER ANDRES",
            "LOMBANA MELO ANDRES FELIPE": "ARCOS ARCOS CARLOS DAVID",
            "LOPEZ VELASQUEZ JHON ALEXANDER": "MORENO MARTINEZ SEBASTIAN FELIPE",
            "LUNA PATIÑO SANTIAGO DAVID": "DELGADO MUÑOZ JUAN DAVID",
            "MADROÑERO REINEL KEVIN NICOLAS": "CABRERA NARVAEZ JOSE MANUEL",
            "MAYA DELGADO NICOLAS SANTIAGO": "JARAMILLO DIAZ JUAN FERNANDO",
            "MORENO MARTINEZ SEBASTIAN FELIPE": "ZAMBRANO CAICEDO JUAN MIGUEL",
            "MORILLO BEDOYA SERGIO LUIS": "LUNA PATIÑO SANTIAGO DAVID",
            "MUÑOZ TULCAN JULIANA": "ERAZO CASTRO KAREN BRIGITH",
            "NARVAEZ CABRERA JAIDER ANDRES": "SERRANO TORO JOHAN ALEXANDER",
            "ORTIZ ORTIZ DAVID ESTEBAN": "LAGOS URBANO DANNA NATALY",
            "PASAJENARVAEZ DAVID": "LOMBANA MELO ANDRES FELIPE",
            "QUENAN ALDERETE CARLOS ANDRES": "CORONADO PARRA JUAN SEBASTIAN",
            "SERRANO TORO JOHAN ALEXANDER": "ERASO GRIJALBA JUAN MANUEL",
            "TULCAN CIFUENTES GERMAN ANDRES": "VIVEROS CABRERA ANTHONY JOSE",
            "VALLEJO ZAMORA MARIA ALEJANDRA": "CAICEDO JURADO MARIO ANDRES",
            "VELASQUEZ BENAVIDES VICTOR MANUEL": "MAYA DELGADO NICOLAS SANTIAGO",
            "VIVEROS CABRERA ANTHONY JOSE": "ORTIZ ORTIZ DAVID ESTEBAN",
            "ZAMBRANO CAICEDO JUAN MIGUEL": "MORILLO BEDOYA SERGIO LUIS"
            // Resto de los nombres del cuarto semestre...
        }
    };

    // Llenar el dropdown de nombres basados en el semestre seleccionado
    if (semester in friends) {
        Object.keys(friends[semester]).forEach(function (name) {
            const option = document.createElement("option");
            option.value = name;
            option.textContent = name;
            nameSelect.appendChild(option);
        });
    }
});

document.getElementById("secretForm").addEventListener("submit", function (event) {
    event.preventDefault();

    const semester = document.getElementById("semester").value;
    const name = document.getElementById("name").value;

    // JSON con datos ficticios de amigos secretos
    const friends = {
        "primero": {
            "BENAVIDES GARCIA LEANDRO DANIEL": "HOYOS PATIÑO CARLOS ALBERTO",
            "BENAVIDES VELASQUEZ DANIEL FERNANDO": "VALLEJO HURTADO IVAN DAVID",
            "BURBANO MORA JUAN GUILLERMO": "PANTOJA BASTIDAS JORMAN JHONATHAN",
            "CADENA SANCHEZ NICOLAS SANTIAGO": "SIERRA NARVAEZ JUAN CARLOS",
            "CASANOVA AYALA CHARLI REINALDO": "ROSADA RODRIGUEZ NICOLAS ALEJANDRO",
            "CORAL SILVA CRISTIAN CAMILO": "OBANDO ROSERO GABRIEL DAVID",
            "CORDOBA DIAZ OSCAR JULIAN": "LOPEZ LIMAS DANIA ALEJANDRA",
            "CORONEL DELGADO JAIDER": "OBANDO DIAZ GABRIEL SANTIAGO",
            "DE LA ROSA MAYA JAIRO SEBASTIAN": "HOYOS ESTUPIÑAN JUAN FELIPE",
            "DIAZ ORTIZ ANGELA GABRIELA": "TUTALCHA CUATIN AMANDA YANEL",
            "ENRIQUEZ ESPAÑA MIGUEL ANGEL ANDRES": "OBANDO ALVARO KEVIN",
            "ERAZO MONTEZUMA JUAN JOSE": "ROSADA RODRIGUEZ NICOLAS ALEJANDRO",
            "HOYOS ESTUPIÑAN JUAN FELIPE": "MARTINEZ BENAVIDES SAMUEL",
            "HOYOS PATIÑO CARLOS ALBERTO": "ORTEGA CHAMORRO JESUS ALEJANDRO",
            "LOPEZ BOTINA JAVIER ALDAIR": "SALAS TORRES JUAN MARCOS",
            "LOPEZ LIMAS DANIA ALEJANDRA": "CORONEL DELGADO JAIDER",
            "MARTINEZ BENAVIDES SAMUEL": "CADENA SANCHEZ NICOLAS SANTIAGO",
            "MAYA LASSO JHON DEIBY": "CORDOBA DIAZ OSCAR JULIAN",
            "MEFLEH MOREANO HANAN LUCIA": "BENAVIDES VELASQUEZ DANIEL FERNANDO",
            "MORA OBANDO ALVARO KEVIN": "ORTEGA GOMEZ CARLOS EDUARDO",
            "OBANDO ALVARO KEVIN": "MEFLEH MOREANO HANAN LUCIA",
            "OBANDO DIAZ GABRIEL SANTIAGO": "DE LA ROSA MAYA JAIRO SEBASTIAN",
            "OBANDO ROSERO GABRIEL DAVID": "BURBANO MORA JUAN GUILLERMO",
            "OJEDA OSORIO YOSEPH DAVID": "SANTOS MUTIS DANNA MARCELA",
            "ORTEGA CHAMORRO JESUS ALEJANDRO": "ENRIQUEZ ESPAÑA MIGUEL ANGEL ANDRES",
            "ORTEGA GOMEZ CARLOS EDUARDO": "ERAZO MONTEZUMA JUAN JOSE",
            "PANTOJA BASTIDAS JORMAN JHONATHAN": "SIERRA NARVAEZ JUAN CARLOS",
            "ROSADA RODRIGUEZ NICOLAS ALEJANDRO": "CASANOVA AYALA CHARLI REINALDO",
            "ROSALES SOLARTE DAVID SANTIAGO": "LOPEZ BOTINA JAVIER ALDAIR",
            "SALAS TORRES JUAN MARCOS": "CORAL SILVA CRISTIAN CAMILO",
            "SANTACRUZ GORDILLO DANIEL FELIPE": "MAYA LASSO JHON DEIBY",
            "SANTACRUZ VELA JOSE GABRIEL": "OJEDA OSORIO YOSEPH DAVID",
            "SANTOS MUTIS DANNA MARCELA": "LOPEZ LIMAS DANIA ALEJANDRA",
            "SIERRA NARVAEZ JUAN CARLOS": "BENAVIDES GARCIA LEANDRO DANIEL",
            "TUTALCHA CUATIN AMANDA YANEL": "SANTACRUZ GORDILLO DANIEL FELIPE",
            "VALLEJO HURTADO IVAN DAVID": "ROSALES SOLARTE DAVID SANTIAGO"
        },
        "cuarto": {
            "ALVAREZ SOLARTE VALENTINA": "CEBALLOS ERASO JULIAN ANDRES",
            "ARCOS ARCOS CARLOS DAVID": "ESCOBAR ENRIQUEZ DIEGO FERNANDO",
            "CABRERA NARVAEZ JOSE MANUEL": "GORDILLO ROSERO CAMILO SEBASTIAN",
            "CAICEDO JURADO MARIO ANDRES": "JARAMILLO LUNA ANYELI VANESA",
            "CEBALLOS ERASO JULIAN ANDRES": "LOPEZ VELASQUEZ JHON ALEXANDER",
            "CORONADO PARRA JUAN SEBASTIAN": "MADROÑERO REINEL KEVIN NICOLAS",
            "DELGADO MUÑOZ JUAN DAVID": "MUÑOZ TULCAN JULIANA",
            "ERASO GRIJALBA JUAN MANUEL": "VELASQUEZ BENAVIDES VICTOR MANUEL",
            "ERAZO CASTRO KAREN BRIGITH": "ALVAREZ SOLARTE VALENTINA",
            "ESCOBAR ENRIQUEZ DIEGO FERNANDO": "QUENAN ALDERETE CARLOS ANDRES",
            "GORDILLO ROSERO CAMILO SEBASTIAN": "TULCAN CIFUENTES GERMAN ANDRES",
            "JARAMILLO DIAZ JUAN FERNANDO": "VALLEJO ZAMORA MARIA ALEJANDRA",
            "JARAMILLO LUNA ANYELI VANESA": "PASAJENARVAEZ DAVID",
            "LAGOS URBANO DANNA NATALY": "NARVAEZ CABRERA JAIDER ANDRES",
            "LOMBANA MELO ANDRES FELIPE": "ARCOS ARCOS CARLOS DAVID",
            "LOPEZ VELASQUEZ JHON ALEXANDER": "MORENO MARTINEZ SEBASTIAN FELIPE",
            "LUNA PATIÑO SANTIAGO DAVID": "DELGADO MUÑOZ JUAN DAVID",
            "MADROÑERO REINEL KEVIN NICOLAS": "CABRERA NARVAEZ JOSE MANUEL",
            "MAYA DELGADO NICOLAS SANTIAGO": "JARAMILLO DIAZ JUAN FERNANDO",
            "MORENO MARTINEZ SEBASTIAN FELIPE": "ZAMBRANO CAICEDO JUAN MIGUEL",
            "MORILLO BEDOYA SERGIO LUIS": "LUNA PATIÑO SANTIAGO DAVID",
            "MUÑOZ TULCAN JULIANA": "ERAZO CASTRO KAREN BRIGITH",
            "NARVAEZ CABRERA JAIDER ANDRES": "SERRANO TORO JOHAN ALEXANDER",
            "ORTIZ ORTIZ DAVID ESTEBAN": "LAGOS URBANO DANNA NATALY",
            "PASAJENARVAEZ DAVID": "LOMBANA MELO ANDRES FELIPE",
            "QUENAN ALDERETE CARLOS ANDRES": "CORONADO PARRA JUAN SEBASTIAN",
            "SERRANO TORO JOHAN ALEXANDER": "ERASO GRIJALBA JUAN MANUEL",
            "TULCAN CIFUENTES GERMAN ANDRES": "VIVEROS CABRERA ANTHONY JOSE",
            "VALLEJO ZAMORA MARIA ALEJANDRA": "CAICEDO JURADO MARIO ANDRES",
            "VELASQUEZ BENAVIDES VICTOR MANUEL": "MAYA DELGADO NICOLAS SANTIAGO",
            "VIVEROS CABRERA ANTHONY JOSE": "ORTIZ ORTIZ DAVID ESTEBAN",
            "ZAMBRANO CAICEDO JUAN MIGUEL": "MORILLO BEDOYA SERGIO LUIS"
            // Resto de los nombres del cuarto semestre...
        }
    };

    // Seleccionar un amigo secreto que no sea el mismo nombre ingresado
    const friendName = friends[semester][name] || "No has ingresado tu nombre correctamente.";

    document.getElementById("friendName").textContent = friendName;
    document.getElementById("result").classList.remove("hidden");
});
